3 sprint project done
Zheleznikov/space-burger pull request #4
Opened 2023-04-29 17:55 UTC by Zheleznikov

Добрый день.

2023-04-30 02:43 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/xNQRcTbTo40hSQ> - Нужно поправить шрифт в компоненте `header`;

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);

- В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/WYIToHVOQHYTZQ>;

- Если пользователь отредактировал данные в форме, то появляются кнопки "Отмена" и "Сохранить".
  При нажатии кнопки "Сохранить" на странице профиля пользователя отправляется соответствующий запрос к Api содержащий измененные данные.
  При нажатии кнопки "Отмена" значения полей формы возвращаются в состояние до редактирования, а кнопки "Отмена" и "Сохранить" скрываются.
  Кнопки не должны быть постоянно.

- Вам нужно проверить запросы, некоторые их них (`POST /login`, `POST /order`, `PATCH /user`) должны посылать `accessToken`. При запросах использующих accessToken проверяется ответ сервера. Если время жизни токена истекло, то выполняется запрос обновления токена и повторяется запрос, который не был выполнен успешно.

- Если значения нет, то нужно использовать null, а не пустой объект.

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-04-30 02:43 UTC, ArslanDev666 commented on src/client/api-client.jsx
> +    }
**Надо исправить:**

Здесь и далее. Там, где вы передаёте токен в запрос.

Вы должны делать проверку на истечение токена, если токен истёк, вы должны получить новый, и снова сделать запрос.

Лучше сделать отдельный запрос, который будет проверять истёк ли токен, или нет.
Обрабатывать ошибки запросов и при возникновении ошибки jwt expired и вызывать обновление токена при ошибке

Для этого используйте обертку над fetch, примерно такую

```js
// например вот так
export const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options);
    return await checkResponse(res);
  } catch (err) {
    if (err.message === 'jwt expired') {
      const refreshData = await refreshToken();
      if (!refreshData.success) {
        Promise.reject(refreshData);
      }
      localStorage.setItem('refreshToken', refreshData.refreshToken);
      setCookie('accessToken', refreshData.accessToken);
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options);
      return await checkResponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```

2023-04-30 02:43 UTC, ArslanDev666 commented on src/components/app/app.jsx
> +    useEffect(() => dispatch(defineUSer()), [dispatch]);
**Можно лучше:**

А почему в одном и том же `useEffect` это не сделали?

2023-04-30 02:43 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                                                             : null
**Можно лучше:**

попробуйте положить `refs` в объект, и просто доставайте их по ключу

Либо, как вы могли заметить эта часть кода повторяется, поэтому её можно вынести в отдельный компонент `ingredients-category`, тогда реф можно спокойно прокидывать через пропс, без всяких циклов и т.п.)) 

```js
const mains = ingredients.filter(ingredient => ingredient.type === 'main')
// ...

<IngredientsCategory containerRef={mainRef} ingredients={mains} ... />
<IngredientsCategory containerRef={mainRef} ingredients={sauces} ... />
<IngredientsCategory containerRef={bunRef} ingredients={buns} ... />
```

2023-04-30 02:43 UTC, ArslanDev666 commented on src/pages/Protected.jsx
> +}
**Надо исправить:**

попробуйте дожидаться пока произойдет запрос у пользователя, у вас есть `isAuth`, но он избыточен, т.к. можно сделать из `user`, просто `null`, а не давать ему какие-то начальные поля (`name`, `email`). А вот из `isAuth` можно сделать флаг, который будет говорить о том, выполнился ли запрос или нет (неважно успешно или с ошибкой, важен сам факт выполнения). 

Вот пример: 

```jsx
const ProtectedRoute = ({ onlyUnAuth = false, children }) => {
  const isAuthChecked = useSelector((state) => state.user.isAuthChecked);
  const user = useSelector((state) => state.user.data);
  const location = useLocation();

  if (!isAuthChecked) {
    return <Preloader />;
  }

  if (onlyUnAuth && user) {
    const { from } = location.state || { from: { pathname: "/" } };
    return <Navigate to={from} />;
  }

  if (!onlyUnAuth && !user) {
    return (
      <Navigate 
        to="/login"
        state={{ from: location }}
      />
    );
  }

  return children;
};

export default ProtectedRoute;
```

2023-04-30 02:43 UTC, ArslanDev666 commented on src/pages/forgot-password/forgot-password.jsx
> +        [isPending, isError])
**Можно лучше:**

Тут лучше использовать `useMemo`))

2023-04-30 02:43 UTC, ArslanDev666 commented on src/pages/forgot-password/forgot-password.jsx
> +                    }}
**Можно лучше:**

лучше вынести обработчик событий в отдельную функцию.

2023-04-30 02:43 UTC, ArslanDev666 commented on src/pages/forgot-password/forgot-password.jsx
> +    const {isPending, isError, error, reset, isAuth} = useSelector(userStateSelector);
**Можно лучше:**

Советую прочесть статью: https://habr.com/ru/articles/722444/

2023-04-30 02:43 UTC, ArslanDev666 commented on src/pages/login-page/login-page.jsx
> +    }, [isAuth, navigate])
**Надо исправить:**

Это нужно убрать)) Проблема была в компоненте `protected`, я попробовал подсказать вам как решить эту проблему))

2023-04-30 02:43 UTC, ArslanDev666 commented on src/pages/profile/nested/user-info.jsx
> +    const [password, setPassword] = useState('');
**Можно лучше:**

Можно сделать универсальный кастомный хук для контроля любого количества инпутов в любых формах:

```js
export function useForm(inputValues) {
  const [values, setValues] = useState(inputValues);

  const handleChange = event => {
    const { value, name } = event.target;
    setValues({ ...values, [name]: value });
  };
  return { values, handleChange, setValues };
}
```

Этот код помещают в отдельный файл useForm.js в папке hooks и импортируют функцию туда, где нужно контролировать инпуты

И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:

```js
const { values, handleChange, setValues } = useForm({...});
```

2023-04-30 11:16 UTC, Zheleznikov commented on src/components/app/app.jsx
> +    useEffect(() => dispatch(defineUSer()), [dispatch]);
Исправил

2023-04-30 15:34 UTC, Zheleznikov commented on src/pages/Protected.jsx
> +}
Круто. Спасибо.
Немного докрутил изменил код. `!isAuthChecked` заменил на `isPending`

2023-04-30 15:41 UTC, Zheleznikov commented on src/pages/forgot-password/forgot-password.jsx
> +        [isPending, isError])
Спасибо. 
Убрал всю эту логику за спинер :)

2023-04-30 15:42 UTC, Zheleznikov commented on src/pages/forgot-password/forgot-password.jsx
> +    const {isPending, isError, error, reset, isAuth} = useSelector(userStateSelector);
Спасибо.
Где-то добавил shallowEqual, где-то сделал более точечные селекторы.

2023-04-30 15:44 UTC, Zheleznikov commented on src/pages/login-page/login-page.jsx
> +    }, [isAuth, navigate])
Убрал все подобное :)

2023-04-30 15:44 UTC, Zheleznikov commented on src/pages/profile/nested/user-info.jsx
> +    const [password, setPassword] = useState('');
Спасибо за хук

2023-04-30 15:57 UTC, Zheleznikov commented
- > https://disk.yandex.com/i/xNQRcTbTo40hSQ - Нужно поправить шрифт в компоненте header;

Исправил


- > Вы должны добавлять в хедер запроса POST /orders, токен пользователя Bearer ..., чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);

Исправил. Посмотрите, как сделал блокировку добавления ингредиентов в конструктор и кнопки.


- > В запросе POST /orders нужно чтобы id у булок были в начале и в конце массива: https://disk.yandex.com/i/WYIToHVOQHYTZQ;

Не исправил. Не могу найти это требование нигде в документации. С точки зрения бизенс-логики тоже непонятно, почему так должно быть. Бэк разве не сможет по айдишникам достать мета информацию из БД?


- > Если пользователь отредактировал данные в форме, то появляются кнопки "Отмена" и "Сохранить".
При нажатии кнопки "Сохранить" на странице профиля пользователя отправляется соответствующий запрос к Api содержащий измененные данные.
При нажатии кнопки "Отмена" значения полей формы возвращаются в состояние до редактирования, а кнопки "Отмена" и "Сохранить" скрываются.
Кнопки не должны быть постоянно.

Исправил. Вообще требования разбросаны по 3 документам. Хер найдешь, где что смотреть.


- > Вам нужно проверить запросы, некоторые их них (POST /login, POST /order, PATCH /user) должны посылать accessToken. При запросах использующих accessToken проверяется ответ сервера. Если время жизни токена истекло, то выполняется запрос обновления токена и повторяется запрос, который не был выполнен успешно.

Исправил `POST /order, PATCH /user` . `POST /login`  - не исправил. Предполагаю, что вы имели ввиду `POST /user`  Т.к. при логировании accessToken еще нет, а при обновлении информации о пользователе есть.

2023-04-30 16:13 UTC, Zheleznikov commented on src/client/api-client.jsx
> +    }
Обернул 3 запроса в похожую штуку:
- создание заказа
- получение данных о пользователе
- обновление данных о пользователе.

Вроде работает, но сложно отдебажить - каждые 20 минут проблематично ждать. Заглушку тоже не хотел писать. 
Вроде работает :)

2023-04-30 16:47 UTC, Zheleznikov commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                                                             : null
- > попробуйте положить refs в объект, и просто доставайте их по ключу

Стало лучше, спасибо :)

Вторую часть не понял, но я и забыл, как оно работает :)

2023-04-30 16:50 UTC, Zheleznikov commented on src/client/api-client.jsx
> +    }
Мне не нравится в этом варианте только то, что у меня теперь логика работы с куками размывается по "классам": часть в экшн-крейторах, часть в клиентах для апи.

2023-04-30 16:59 UTC, Zheleznikov commented on src/client/api-client.jsx
> +    }
![it-works](https://user-images.githubusercontent.com/55275237/235366076-5534671a-9ab0-4881-afe1-17e9df6030ea.PNG)

2023-04-30 17:59 UTC, Zheleznikov commented
Добрый день. Спасибо, что проверили  работу за ночь :) Утром как раз встал и продолжил.

2023-05-01 04:22 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                                                             : null
По поводу второй части, обычно из этой части кода: https://disk.yandex.com/i/J-l4EpR_FIf1dg, делают отдельный компонент `ingredients-category`, и всё что нужно прокидывают туда. Это намного проще читается, чем цикл, можно конечно и тут циклом сделать, но я практически всегда отдаю предпочтение читабельности кода)

```js
const mains = ingredients.filter(ingredient => ingredient.type === 'main')
// ...

<IngredientsCategory containerRef={mainRef} ingredients={mains} title="Начинки" ... />
<IngredientsCategory containerRef={sauceRef} ingredients={sauces} title="Соусы" ... />
<IngredientsCategory containerRef={bunRef} ingredients={buns} title="Булки" ... />
```

2023-05-01 04:36 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-05-01 04:36 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    useMemo(() => {
**Надо исправить:**

я вроде бы ничего не говорил про это место))

Тут как раз таки нужно использовать `useEffect`, а не `useMemo`, мы ведь не получаем конечное значение.

2023-05-01 04:36 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
>      const bunsData = useSelector(getBunsInConstructor);
**Можно лучше:**

тут лучше хранить на массив, а просто булку - объект)) т.к. булка всё равно одна и та же.

2023-05-01 04:36 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
>      }
👍

2023-05-01 04:44 UTC, ArslanDev666 commented
> - Не исправил. Не могу найти это требование нигде в документации. С точки зрения бизенс-логики тоже непонятно, почему так должно быть. Бэк разве не сможет по айдишникам достать мета информацию из БД?

Я ответил наставнику/ментору, продублирую сюда) Если заглянуть немного далее, в спринт где пользователь будет делать страницу `/feed` , у нас будет вот такая разница (id-шники будут идти в том порядке, в котором мы их отправили), обрати внимание на очередность булок https://disk.yandex.com/i/yt-l_db7cAZgxg, https://disk.yandex.com/i/jRMc4awGZRi-iw.

> - Исправил. Вообще требования разбросаны по 3 документам. Хер найдешь, где что смотреть.

Всё максимально приближено к реальному проекту :)

> - Исправил POST /order, PATCH /user . POST /login - не исправил. Предполагаю, что вы имели ввиду POST /user Т.к. при логировании accessToken еще нет, а при обновлении информации о пользователе есть.

Да всё верно, маленько опечатался)

> - Вроде исправил :). todo - это ведь не комментарий, а напоминание, что надо сделать, разве нет?

 TODO - это напоминание, но у каждой команды/проекта свой `style-code`, поэтому везде может быть по-разному. Ну и лично моё мнение, todo тут больше подходит, если допустим баг в какой-то библиотеке, и ты отключил линтер именно из-за него. И со временем когда баг из библиотеки исчезнет, ты вспомнишь про этот кусок кода, и поправишь))

2023-05-01 05:57 UTC, Zheleznikov commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    useMemo(() => {
Исправил

2023-05-01 06:00 UTC, Zheleznikov commented
Сделал два фикса по комментариям.

**По поводу булок в начале в и в конце**
Спасибо, исправил. Просто нужно было выяснить, почему. А-то вы говорите так, потом придет другой ревьювер, скажет, зачем это, а я ему что скажу :))

**По поводу useMemo вместо useEffect** 
Исправил. Но я пока плаваю в useMemo, не очень понимаю, когда его использовать. Попробовал - вроде ничего не сломалось, подумал, мемоиизация это же хорошо и оставил :)

2023-05-01 06:00 UTC, Zheleznikov commented on src/components/burger-constructor/burger-constructor.jsx
>      }
Исправил булки

2023-05-01 06:02 UTC, Zheleznikov commented on src/components/burger-constructor/burger-constructor.jsx
>      const bunsData = useSelector(getBunsInConstructor);
Ну можно :) Ну на такой вариант уже и расчет стоимости вроде завязан...

2023-05-01 06:05 UTC, Zheleznikov commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                                                             : null
Понял. Видимо лучше сделать так. Но уже немного одурел от этого спринта :)

2023-05-01 09:48 UTC, Zheleznikov commented
Еще заметил одну неприятность. При создании заказа можно было удалить мясо-соусы из конструктора - пофиксил это.

2023-05-02 08:28 UTC, merged