refactor from js to ts
Zheleznikov/space-burger pull request #5
Opened 2023-05-21 19:41 UTC by Zheleznikov

Добрый день.
Ну со скрипом конечно мне дался этот рефакторинг...

2023-05-21 20:12 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Хорошая типизация компонентов
- Хорошая типизация утилитарных функций, особенно для работы с куками

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- В проекте много `any` от которых можно без проблем избавиться. Часть таких моментов отмечены комментариями в `pull-request`. `any` в блоке `catch` это не касается.
- У вас файлы без разметки имеют расширение `jsx`- хотя должны просто - `js`

<img width="690" alt="Снимок экрана 2023-05-21 в 23 10 26" src="https://github.com/Zheleznikov/space-burger/assets/60173362/0d228e18-7b2f-4b3f-9048-65ce992386d9">

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-21 20:12 UTC, andryxxa93 commented on src/components/modal/modal.tsx
> +    const handleEsc = (e: any) => e.key === 'Escape' && (closeModal && closeModal());
**Необходимо исправить**
Тут `any` нужно заменить на `KeyboardEvent`

2023-05-21 20:12 UTC, andryxxa93 commented on src/pages/forgot-password/forgot-password.tsx
> +    const resetPassword = (e: any) => {
**Необходимо исправить**
Во всех подобных местах вам надо поменять `any` на `FormEvent`

2023-05-21 20:12 UTC, andryxxa93 commented on src/pages/forgot-password/forgot-password.tsx
> +    const changeEmailHandler = (e : any) => {
**Необходимо исправить**
В подобных местах необходимо поставить `React.ChangeEvent<HTMLInputElement>`

2023-05-21 20:12 UTC, andryxxa93 commented on src/hooks/use-form.tsx
> +    const handleChange = (event: any) => {
**Необходимо исправить**
Тут можно использовать `React.ChangeEvent<HTMLInputElement>`

2023-05-21 20:30 UTC, Zheleznikov commented
Спасибо.

Переименовал файлы `*.jsx` в `*.js`.

2023-05-21 20:30 UTC, Zheleznikov commented on src/hooks/use-form.tsx
> +    const handleChange = (event: any) => {
Исправил

2023-05-21 20:31 UTC, Zheleznikov commented on src/pages/forgot-password/forgot-password.tsx
> +    const changeEmailHandler = (e : any) => {
Исправил здесь и в аналогичных инпутах

2023-05-21 20:31 UTC, Zheleznikov commented on src/pages/forgot-password/forgot-password.tsx
> +    const resetPassword = (e: any) => {
Исправил здесь и в аналогичных сабмитах

2023-05-21 20:31 UTC, Zheleznikov commented on src/components/modal/modal.tsx
> +    const handleEsc = (e: any) => e.key === 'Escape' && (closeModal && closeModal());
Исправил, спасибо

2023-05-22 09:07 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-22 09:13 UTC, merged